image: python:latest

before_script:
  - python3 -V
  - python3 -m pip install --user pipenv
  - python3 -m pipenv install --dev
  - export VENV_HOME_DIR=$(python3 -m pipenv --venv)

test:
  script:
  - source $VENV_HOME_DIR/bin/activate
  - python3 -m prospector

run:
  script:
  - source $VENV_HOME_DIR/bin/activate
  - python3 -m scan --help
