image: python:latest

before_script:
  - python3.5 -V
  - python3.5 -m pip install --user pipenv
  - python3.5 -m pipenv install --dev
  - export VENV_HOME_DIR=$(python3.5 -m pipenv --venv)

test:
  script:
  - source $VENV_HOME_DIR/bin/activate
  - python3.5 -m flake8 --ignore=E501

run:
  script:
  - source $VENV_HOME_DIR/bin/activate
  - python3.5 -m app --help
